name: kelime-savaslari-backend-dev

services:
  mongo:
    image: mongo:8.0.3
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - kelime-savaslari-backend
  api:
    build:
      context: ./
      target: development
    restart: unless-stopped
    env_file: ./.env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - kelime-savaslari-backend
    depends_on:
      - mongo

volumes:
  mongo_data:
networks:
  kelime-savaslari-backend:
    driver: bridge
